apiVersion: v1
kind: Service
metadata:
  name: pokemonsearch
  namespace: default
spec:
  type: LoadBalancer  # Esto crea una IP pública en AKS
  selector:
    app: pokemonsearch
  ports:
  - protocol: TCP
    port: 80        # Puerto expuesto públicamente
    targetPort: 80  # Puerto dentro del contenedor
